services:
  - type: web
    name: facial-expression-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PORT
        value: 8501
